name: ccip
services:
  anaconda:
    build: ./docker/anaconda
    image: ccip-anaconda:1.0
    container_name: dev_env
    volumes:
      # 當下的專案資料夾目錄掛載到docker裡頭的/opt/ccclub資料夾底下
      - ./:/opt/ccclub
    ports:
      - "8887:8888" # jupyterlab
    mem_limit: 4g

  chrome:
    build: ./docker/selenium
    image: ccip-chrome:1.0
    container_name: crawler
    shm_size: 2gb
    ports:
      - "4443:4444"
      - "7901:7900"
