swagger: "2.0"
info:
  description: "This is a sample server Backtest server."
  version: "1.0.0"
  title: "Backtest API"
host: "localhost:5555"
basePath: "/"
schemes:
  - "http"
paths:
  /:
    get:
      summary: "Home endpoint"
      description: "Returns a welcome message."
      responses:
        200:
          description: "Home endpoint, returns a welcome message."
          content:
            text/plain:
              schema:
                type: string
                example: "Backtest Running!!!"
  /one_stock:
    get:
      summary: "Run backtest for one stock"
      parameters:
        - name: id
          in: query
          type: string
          description: "The stock ID to backtest."
          required: false
          default: '0050'
        - name: amount
          in: query
          type: integer
          description: "The amount to buy."
          required: false
          default: 3000
        - name: date
          in: query
          type: integer
          description: "The buy date."
          required: false
          default: 5
        - name: duration
          in: query
          type: integer
          description: "The duration in years."
          required: false
          default: 10
      responses:
        200:
          description: "The backtest results."
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: "The stock ID."
                    example: '0050'
                  info:
                    type: string
                    description: "Information about the backtest."
                  analysis:
                    type: string
                    description: "Analysis of the backtest results."
                  log:
                    type: string
                    description: "Log of the backtest process."
